name: Unittests & Auto-publish

# Allow to trigger the workflow manually (e.g. when deps changes)
on: [push, workflow_dispatch]

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    # Install deps
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        # Uncomment to cache of pip dependencies (if tests too slow)
        # cache: pip
        # cache-dependency-path: '**/pyproject.toml'

    - run: pip --version
    - run: pip install -e .[dev]
    - run: pip freeze

    # Run tests (in parallel)
    # * `/tests/` subfolder contains end-to-end tests which are to big to run.
    # * Sampler and transformer tests are disabled because they are using the legacy API.
    # TODO(epot): Restore _interceptors_test.
    - name: Run core tests
      run: |
        pytest -vv -n auto \
          --ignore=gemma/gm/tests/ \
          --ignore=gemma/peft/_interceptors_test.py \
          --ignore=gemma/sampler_test.py \
          --ignore=gemma/transformer_test.py

  # Auto-publish when version is increased
  publish-job:
    # Only try to publish if:
    # * Repo is self (prevents running from forks)
    # * Branch is `main`
    if: |
      github.repository == 'google-deepmind/gemma'
      && github.ref == 'refs/heads/main'
    needs: pytest-job  # Only publish after tests are successful
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30

    steps:
    # Publish the package (if local `__version__` > pip version)
    - uses: etils-actions/pypi-auto-publish@v1
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        parse-changelog: false
      id: publish

    - name: Generate Changelog
      if: steps.publish.outputs.is-released == 'true'
      uses: mikepenz/release-changelog-builder-action@v4
      id: build_changelog
      with:
        mode: "COMMIT"
        configurationJson: |
          {
            "template": "# Changes\n\n#{{categories}}\n",
            "categories": [
              {
                "title": "## Features",
                "labels": ["^Add", "^Adding", "^Introduce", "^Expose", "^Support", "^New", "^Feat", "^Feature", "^Allow", "^Implement", "^Enable"]
              },
              {
                "title": "## Bug Fixes",
                "labels": ["^[Ff]ix", "^Fixing", "^Correct", "^Resolve", "^Patch", "^Bug"]
              },
              {
                "title": "## Documentation",
                "labels": ["^Doc", "^Docs", "^Document", "^Update README", "^More doc", "^Clarify", "^Updating"]
              },
              {
                "title": "## Maintenance",
                "labels": ["^Remove", "^Modify", "^Modifying", "^Refactor", "^Replace", "^Update", "^Upgrade", "^Bump", "^Misc", "^Temporary", "^Chore", "^Test", "^CI", "^Rename", "^Internal", "^Configure", "^Filter", "^Make", "^Log"]
              }
            ],
            "ignore_emoji": true,
            "pr_template": "- #{{TITLE}}",
            "empty_template": "- No changes found for this category."
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Release
      if: steps.publish.outputs.is-released == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.publish.outputs.version }}
        body: ${{ steps.build_changelog.outputs.changelog }}
        token: ${{ secrets.GITHUB_TOKEN }}
